/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package talkerclientapp;

import common.Contact;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author amster
 */
public class EditContactFrame extends javax.swing.JFrame {

    Contact selectedContact;

    public EditContactFrame() {
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * Creates new form AddContactFrame
     *
     * @param contact
     */
    public EditContactFrame(Contact contact) {
        initComponents();
        selectedContact = contact;

//        selectedContact = MainWindowFrame.getSelectedContact();
        if (selectedContact != null) {
            if (selectedContact.talkerNumber != null) {
                talkerNumberTextField.setText(selectedContact.talkerNumber.toString());
            }

            if (selectedContact.phoneNumber != null) {
                phoneNumberTextField.setText(selectedContact.phoneNumber.toString());
            }

            if (selectedContact.firstName != null) {
                firstNameTextField.setText(selectedContact.firstName);
            }

            if (selectedContact.lastName != null) {
                lastNameTextField.setText(selectedContact.lastName);
            }

            if (selectedContact.displayedName != null) {
                displayedNameTextField.setText(selectedContact.displayedName);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        talkerNumberTextField = new javax.swing.JTextField();
        talkerNumberLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        displayedNameTextField = new javax.swing.JTextField();
        displayedNameLabel = new javax.swing.JLabel();
        saveContactButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edytuj kontakt");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dane kontaktu"));
        jPanel1.setName(""); // NOI18N

        talkerNumberTextField.setPreferredSize(new java.awt.Dimension(200, 27));
        talkerNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                talkerNumberTextFieldActionPerformed(evt);
            }
        });

        talkerNumberLabel.setText("Numer Talker");
        talkerNumberLabel.setPreferredSize(new java.awt.Dimension(200, 27));

        firstNameLabel.setText("Imię");
        firstNameLabel.setMinimumSize(new java.awt.Dimension(200, 27));
        firstNameLabel.setPreferredSize(new java.awt.Dimension(200, 27));

        firstNameTextField.setMinimumSize(new java.awt.Dimension(200, 27));
        firstNameTextField.setPreferredSize(new java.awt.Dimension(200, 27));
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });
        firstNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameTextFieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstNameTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstNameTextFieldKeyReleased(evt);
            }
        });

        lastNameLabel.setText("Nazwisko");
        lastNameLabel.setMinimumSize(new java.awt.Dimension(200, 27));
        lastNameLabel.setPreferredSize(new java.awt.Dimension(200, 27));

        lastNameTextField.setMinimumSize(new java.awt.Dimension(200, 27));
        lastNameTextField.setPreferredSize(new java.awt.Dimension(200, 27));
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });
        lastNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameTextFieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lastNameTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastNameTextFieldKeyReleased(evt);
            }
        });

        phoneNumberLabel.setText("Nr telefonu");
        phoneNumberLabel.setMinimumSize(new java.awt.Dimension(200, 27));
        phoneNumberLabel.setPreferredSize(new java.awt.Dimension(200, 27));

        phoneNumberTextField.setMinimumSize(new java.awt.Dimension(200, 27));
        phoneNumberTextField.setPreferredSize(new java.awt.Dimension(200, 27));
        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });

        displayedNameTextField.setMinimumSize(new java.awt.Dimension(200, 27));
        displayedNameTextField.setPreferredSize(new java.awt.Dimension(200, 27));
        displayedNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayedNameTextFieldActionPerformed(evt);
            }
        });

        displayedNameLabel.setText("Nazwa wyświetlana");
        displayedNameLabel.setMinimumSize(new java.awt.Dimension(200, 27));
        displayedNameLabel.setPreferredSize(new java.awt.Dimension(200, 27));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(talkerNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(talkerNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayedNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayedNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(talkerNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(talkerNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displayedNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayedNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveContactButton.setText("Zapisz");
        saveContactButton.setPreferredSize(new java.awt.Dimension(60, 29));
        saveContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveContactButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Anuluj");
        cancelButton.setPreferredSize(new java.awt.Dimension(60, 29));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveContactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveContactButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void talkerNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_talkerNumberTextFieldActionPerformed
    {//GEN-HEADEREND:event_talkerNumberTextFieldActionPerformed
    }//GEN-LAST:event_talkerNumberTextFieldActionPerformed

    private void displayedNameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_displayedNameTextFieldActionPerformed
    {//GEN-HEADEREND:event_displayedNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayedNameTextFieldActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_firstNameTextFieldActionPerformed
    {//GEN-HEADEREND:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lastNameTextFieldActionPerformed
    {//GEN-HEADEREND:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
    {//GEN-HEADEREND:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveContactButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveContactButtonActionPerformed
    {//GEN-HEADEREND:event_saveContactButtonActionPerformed

        try {
            if (!talkerNumberTextField.getText().equals("")) {
                selectedContact.talkerNumber = Integer.parseInt(talkerNumberTextField.getText());
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Numer Talker nie może być pusty", "Talker", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(new JFrame(), "Niepoprawny numer Talker", "Talker", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!displayedNameTextField.getText().equals("")) {
            selectedContact.displayedName = displayedNameTextField.getText();
        } else {
            JOptionPane.showMessageDialog(this, "Nazwa wyświetlana nie może być pusta.", "Talker", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            if (!phoneNumberTextField.getText().equals("")) {
                selectedContact.phoneNumber = Long.parseLong(phoneNumberTextField.getText());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(new JFrame(), "Niepoprawny numer telefonu", "Talker", JOptionPane.WARNING_MESSAGE);
            return;
        }

        selectedContact.firstName = firstNameTextField.getText();
        selectedContact.lastName = lastNameTextField.getText();

        Main.contactsMap.put(selectedContact.talkerNumber, selectedContact);

        Map changePersonalDataMap = new HashMap();
        changePersonalDataMap.put("receiverNumber", 0);
        changePersonalDataMap.put("senderNumber", Main.myPersonalData.talkerNumber);
        changePersonalDataMap.put("action", "CHANGE_CONTACTS");
        changePersonalDataMap.put("contacts", Main.contactsMap);

        Main.client.sendMessage(changePersonalDataMap);

        File contacts = new File(Main.DIR_TO_SERIALIZED_DATA + "/contacts.dat");

        try {
            contacts.createNewFile();
            ObjectOutput output = new ObjectOutputStream(new FileOutputStream(contacts));
            output.writeObject(Main.contactsMap);
            output.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(AddContactFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AddContactFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        MainWindowFrame.saveContactAfterEdit(selectedContact);
        this.dispose();

    }//GEN-LAST:event_saveContactButtonActionPerformed

    private void firstNameTextFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_firstNameTextFieldKeyPressed
    {//GEN-HEADEREND:event_firstNameTextFieldKeyPressed
    }//GEN-LAST:event_firstNameTextFieldKeyPressed

    private void lastNameTextFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_lastNameTextFieldKeyPressed
    {//GEN-HEADEREND:event_lastNameTextFieldKeyPressed
    }//GEN-LAST:event_lastNameTextFieldKeyPressed

    private void firstNameTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_firstNameTextFieldKeyTyped
    {//GEN-HEADEREND:event_firstNameTextFieldKeyTyped
    }//GEN-LAST:event_firstNameTextFieldKeyTyped

    private void lastNameTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_lastNameTextFieldKeyTyped
    {//GEN-HEADEREND:event_lastNameTextFieldKeyTyped
    }//GEN-LAST:event_lastNameTextFieldKeyTyped

    private void firstNameTextFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_firstNameTextFieldKeyReleased
    {//GEN-HEADEREND:event_firstNameTextFieldKeyReleased
        displayedNameTextField.setText(firstNameTextField.getText() + " " + lastNameTextField.getText());
    }//GEN-LAST:event_firstNameTextFieldKeyReleased

    private void lastNameTextFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_lastNameTextFieldKeyReleased
    {//GEN-HEADEREND:event_lastNameTextFieldKeyReleased
        displayedNameTextField.setText(firstNameTextField.getText() + " " + lastNameTextField.getText());
    }//GEN-LAST:event_lastNameTextFieldKeyReleased

    public static void addContactToTree() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditContactFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditContactFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditContactFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditContactFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EditContactFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel displayedNameLabel;
    private javax.swing.JTextField displayedNameTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JButton saveContactButton;
    private javax.swing.JLabel talkerNumberLabel;
    private javax.swing.JTextField talkerNumberTextField;
    // End of variables declaration//GEN-END:variables
}
