/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package talkerclientapp;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import static talkerclientapp.AES.encrypt;

/**
 *
 * @author amster
 */
public class EditPersonalData extends javax.swing.JFrame {

    MainWindowFrame mainWindowFrame;

    /**
     * Creates new form AddContactFrame
     */
    public EditPersonalData(MainWindowFrame mainWindowFrame) {

        initComponents();
        
        birthDateLabel.setIcon(new ImageIcon(Main.class.getResource("/resources/images/help_27.png")));
        birthDateLabel.setHorizontalTextPosition(JLabel.LEFT);

        phoneNumberLabel.setIcon(new ImageIcon(Main.class.getResource("/resources/images/help_27.png")));
        phoneNumberLabel.setHorizontalTextPosition(JLabel.LEFT);
        
        passwordLabel.setIcon(new ImageIcon(Main.class.getResource("/resources/images/help_27.png")));
        passwordLabel.setHorizontalTextPosition(JLabel.LEFT);
        
        this.mainWindowFrame = mainWindowFrame;

        this.setLocationRelativeTo(null);

        if (Main.myPersonalData.firstName != null) {
            firstNameTextField.setText(Main.myPersonalData.firstName);
        }
        if (Main.myPersonalData.lastName != null) {
            lastNameTextField.setText(Main.myPersonalData.lastName);
        }
        if (Main.myPersonalData.phoneNumber != null) {
            phoneNumberTextField.setText(Main.myPersonalData.phoneNumber.toString());
        }

        if (Main.myPersonalData.email != null) {
            emailTextField.setText(Main.myPersonalData.email);
        }
        if (Main.myPersonalData.birthDate != null) {
            birthDateTextField.setText(Main.myPersonalData.birthDate.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        birthDateLabel = new javax.swing.JLabel();
        birthDateTextField = new javax.swing.JTextField();
        savePersonalDatatButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edytuj dane personalne");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dane personalne"));
        jPanel1.setName(""); // NOI18N

        firstNameLabel.setText("Imię");
        firstNameLabel.setMinimumSize(new java.awt.Dimension(200, 27));
        firstNameLabel.setPreferredSize(new java.awt.Dimension(200, 27));

        firstNameTextField.setMinimumSize(new java.awt.Dimension(200, 27));
        firstNameTextField.setPreferredSize(new java.awt.Dimension(200, 27));
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });
        firstNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstNameTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstNameTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameTextFieldKeyTyped(evt);
            }
        });

        lastNameLabel.setText("Nazwisko");
        lastNameLabel.setMinimumSize(new java.awt.Dimension(200, 27));
        lastNameLabel.setPreferredSize(new java.awt.Dimension(200, 27));

        lastNameTextField.setMinimumSize(new java.awt.Dimension(200, 27));
        lastNameTextField.setPreferredSize(new java.awt.Dimension(200, 27));
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });
        lastNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lastNameTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastNameTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameTextFieldKeyTyped(evt);
            }
        });

        phoneNumberLabel.setText("Nr telefonu");
        phoneNumberLabel.setToolTipText("Format: 987654321 (dozwolone tylko cyfry)");
        phoneNumberLabel.setMinimumSize(new java.awt.Dimension(200, 27));
        phoneNumberLabel.setPreferredSize(new java.awt.Dimension(200, 27));

        phoneNumberTextField.setMinimumSize(new java.awt.Dimension(200, 27));
        phoneNumberTextField.setPreferredSize(new java.awt.Dimension(200, 27));
        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });

        emailLabel.setText("Email");
        emailLabel.setMinimumSize(new java.awt.Dimension(200, 27));
        emailLabel.setPreferredSize(new java.awt.Dimension(200, 27));

        emailTextField.setMinimumSize(new java.awt.Dimension(200, 27));
        emailTextField.setPreferredSize(new java.awt.Dimension(200, 27));
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        passwordLabel.setText("Hasło");
        passwordLabel.setToolTipText("Podaj nowe hasło. Jeśli chcesz nie chcesz zmieniać hasła - zostaw puste pole.");
        passwordLabel.setMinimumSize(new java.awt.Dimension(200, 27));
        passwordLabel.setPreferredSize(new java.awt.Dimension(200, 27));

        passwordField.setPreferredSize(new java.awt.Dimension(200, 27));

        birthDateLabel.setText("Data urodzenia");
        birthDateLabel.setToolTipText("Format: yyyy-mm-dd");
        birthDateLabel.setMinimumSize(new java.awt.Dimension(200, 27));
        birthDateLabel.setPreferredSize(new java.awt.Dimension(200, 27));

        birthDateTextField.setMinimumSize(new java.awt.Dimension(200, 27));
        birthDateTextField.setPreferredSize(new java.awt.Dimension(200, 27));
        birthDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthDateTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(birthDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(birthDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(434, 434, 434))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(birthDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(birthDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        savePersonalDatatButton.setText("Zapisz");
        savePersonalDatatButton.setPreferredSize(new java.awt.Dimension(60, 29));
        savePersonalDatatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePersonalDatatButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Anuluj");
        cancelButton.setPreferredSize(new java.awt.Dimension(60, 29));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savePersonalDatatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savePersonalDatatButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_firstNameTextFieldActionPerformed
    {//GEN-HEADEREND:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lastNameTextFieldActionPerformed
    {//GEN-HEADEREND:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
    {//GEN-HEADEREND:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void savePersonalDatatButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_savePersonalDatatButtonActionPerformed
    {//GEN-HEADEREND:event_savePersonalDatatButtonActionPerformed

        String passwd = String.valueOf(passwordField.getPassword());

        byte[] encryptedPassword = null;

        Map changePersonalDataMap = new HashMap();
        changePersonalDataMap.put("receiverNumber", 0);
        changePersonalDataMap.put("senderNumber", Main.myPersonalData.talkerNumber);
        changePersonalDataMap.put("action", "CHANGE_PERSONAL_DATA");
        changePersonalDataMap.put("lastName", lastNameTextField.getText());

        if (!emailTextField.getText().equals("") && emailTextField.getText().matches(Main.EMAIL_PATTERN_REGULAR_EXPRESSION)) {
            Main.myPersonalData.email = emailTextField.getText();
            changePersonalDataMap.put("email", emailTextField.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Nieprawidłowy format emaila.", "Talker", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!passwd.equals("")) {

            int i, j;
            j = 16 - passwd.length() % 16;
            for (i = 0; i < j; i++) {
                passwd += "\0";
            }

            try {
                encryptedPassword = encrypt(passwd, AES.encryptionKey);
            } catch (Exception ex) {
                Logger.getLogger(RegistrationFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            changePersonalDataMap.put("password", encryptedPassword);
        }

        if (!firstNameTextField.getText().equals("")) {
            Main.myPersonalData.firstName = firstNameTextField.getText();
            changePersonalDataMap.put("firstName", firstNameTextField.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Imię nie może być puste.", "Talker", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Main.myPersonalData.lastName = lastNameTextField.getText();
        Main.myPersonalData.displayedName = Main.myPersonalData.firstName + " " + Main.myPersonalData.lastName;

        try {
            if (!birthDateTextField.getText().equals("")) {
                Main.myPersonalData.birthDate = Date.valueOf(birthDateTextField.getText());
                changePersonalDataMap.put("birthDate", Date.valueOf(birthDateTextField.getText()));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nieprawidłowy format daty. Wprowadź datę w formacie: yyyy-mm-dd.", "Talker", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            if (!phoneNumberTextField.getText().equals("")) {
                Main.myPersonalData.phoneNumber = Long.parseLong(phoneNumberTextField.getText());
                changePersonalDataMap.put("phoneNumber", phoneNumberTextField.getText());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(new JFrame(), "Nieprawidłowy format numeru telefonu. Dozwolone są tylko cyfry.", "Talker", JOptionPane.WARNING_MESSAGE);
            return;

        }

        File personal_data = new File(Main.DIR_TO_SERIALIZED_DATA + "/personal_data.dat");
        try {
            personal_data.createNewFile();

            ObjectOutput output = new ObjectOutputStream(new FileOutputStream(personal_data));
            output.writeObject(Main.myPersonalData);
            output.close();

        } catch (IOException ex) {
            Logger.getLogger(RegistrationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        Main.client.sendMessage(changePersonalDataMap);

        mainWindowFrame.setTitle(firstNameTextField.getText() + " " + lastNameTextField.getText());
//TODO wyslac dane personalne na server, razem z haslem i zmienic haslo na servie jesli bylo niepuste
        dispose();

    }//GEN-LAST:event_savePersonalDatatButtonActionPerformed

    private void firstNameTextFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_firstNameTextFieldKeyPressed
    {//GEN-HEADEREND:event_firstNameTextFieldKeyPressed
    }//GEN-LAST:event_firstNameTextFieldKeyPressed

    private void lastNameTextFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_lastNameTextFieldKeyPressed
    {//GEN-HEADEREND:event_lastNameTextFieldKeyPressed
    }//GEN-LAST:event_lastNameTextFieldKeyPressed

    private void firstNameTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_firstNameTextFieldKeyTyped
    {//GEN-HEADEREND:event_firstNameTextFieldKeyTyped
    }//GEN-LAST:event_firstNameTextFieldKeyTyped

    private void lastNameTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_lastNameTextFieldKeyTyped
    {//GEN-HEADEREND:event_lastNameTextFieldKeyTyped
    }//GEN-LAST:event_lastNameTextFieldKeyTyped

    private void firstNameTextFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_firstNameTextFieldKeyReleased
    {//GEN-HEADEREND:event_firstNameTextFieldKeyReleased
//        displayedNameTextField.setText( firstNameTextField.getText() + " " + lastNameTextField.getText() );
    }//GEN-LAST:event_firstNameTextFieldKeyReleased

    private void lastNameTextFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_lastNameTextFieldKeyReleased
    {//GEN-HEADEREND:event_lastNameTextFieldKeyReleased
//        displayedNameTextField.setText( firstNameTextField.getText() + " " + lastNameTextField.getText() );
    }//GEN-LAST:event_lastNameTextFieldKeyReleased

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void birthDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthDateTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPersonalData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPersonalData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPersonalData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPersonalData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new EditPersonalData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthDateLabel;
    private javax.swing.JTextField birthDateTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JButton savePersonalDatatButton;
    // End of variables declaration//GEN-END:variables
}
